name: dpdk-wililupy
version: '19.02-0-rc0'
summary: DPDK is a set of libraries and drivers for fast packet processing.
description: DPDK is a set of libraries and drivers for fast packet processing.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
icon: DPDK_logo_vertical_rev_small.png
architectures: [amd64]
base: core18

parts:
  dpdk:
    plugin: python
    python-version: python2
    source: git://dpdk.org/dpdk
    source-type: git
    # source-tag: v17.11 # LTS Version, comment out or change tag to what version you require. 
    build-packages:
      - linux-headers-generic
      - build-essential
      - libnuma-dev
      - pkg-config
      - libelf-dev
    stage-packages:
      - libnuma1
      - pciutils
    override-build: |
      snapcraftctl build
      case "$SNAP_ARCH" in
      amd64)
          target=x86_64-native-linuxapp-gcc
          ;;
      arm64)
          target=arm64-armv8a-linuxapp-gcc
          ;;
      *)
          printf "Unsupported architecture, change snapcraft.yaml\n"
          exit 1
          ;;
      esac
      # RTE_KERNELDIR is only needed if kernel version is not the same as installed on build host
      make install T="$target" \
           DESTDIR="$SNAPCRAFT_PART_INSTALL"/dpdk \
           RTE_KERNELDIR=/usr/src/linux-headers-"$(uname -r)"

apps:
  testpmd:
    command: dpdk/bin/testpmd
    plugs: 
      - network
      - network-bind
      - network-control
      - network-observe
      - hardware-observe
      - hugepages-observe 
      - hugepages-control 
      - process-control
      - system-observe
      - dpdk-control
      - kernel-module-control
      - kernel-module-observe
      
  dpdk-devbind:
    command: dpdk/sbin/dpdk-devbind
    plugs:
      - network
      - network-bind
      - network-control
      - network-observe
      - hardware-observe
      - system-observe
      - dpdk-control
      - kernel-module-control
      - kernel-module-observe
  
  dpdk-setup:
    command: dpdk/share/dpdk/usertools/dpdk-setup.sh
    plugs:
      - network
      - network-bind
      - network-control
      - network-observe
      - hardware-observe
      - system-observe
      - dpdk-control
      - kernel-module-control
      - kernel-module-observe
