name: dpdk-wililupy
version: '19.02-0-rc0'
summary: DPDK is a set of libraries and drivers for fast packet processing.
description: DPDK is a set of libraries and drivers for fast packet processing.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
icon: DPDK_logo_vertical_rev_small.png
architectures: [amd64]

parts:
  dpdk:
    plugin: python
    python-version: python2
    source: git://dpdk.org/dpdk
    source-type: git
    # source-tag: v17.11 # LTS Version, comment out or change tag to what version you require. 
    build-packages:
      - linux-headers-4.4.0-140-generic # Change to the kernel you need
      - build-essential
      - libnuma-dev
      - pkg-config
      - libelf-dev
    stage-packages:
      - libnuma1
    override-build: |
      snapcraftctl build
      make install T=x86_64-native-linuxapp-gcc DESTDIR=$SNAPCRAFT_PART_INSTALL/dpdk RTE_KERNELDIR=/usr/src/linux-headers-4.4.0-140-generic # RTE_KERNELDIR is only needed if kernel version is not the same as installed on build host.

apps:
  testpmd:
    command: dpdk/bin/testpmd
    plugs: 
      - network
      - network-bind
      - network-control
      - network-observe
      - hardware-observe
      - dpdk-observe # commented out until hugepages interface is in snapd
      - dpdk-control # commented out until hugepages interface is in snapd
      - process-control
      - system-observe
      
  dpdk-devbind:
    command: dpdk/sbin/dpdk-devbind
    plugs:
      - network
      - network-bind
      - network-control
      - network-observe
      
